/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Aeroplaine.glb -o Aeroplane.jsx
Manually extended with useFrame-driven idle animations (no baked clips exist on this model).
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useFrame, useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

// Cloudinary-hosted GLB — swap this if you move/re-upload the asset.
const CLOUDINARY_URL = 'https://res.cloudinary.com/db9t6csa1/image/upload/v1783154119/Aeroplaine_vk8lqa.glb'

/* ------------------------------------------------------------------ */
/*  ANIMATION TUNING CONSTANTS                                         */
/*  Everything that controls "feel" lives here so it's easy to tweak.  */
/* ------------------------------------------------------------------ */

// 1) Propeller — fast, continuous, frame-rate independent spin.
const PROPELLER = {
    speed: 55, // rad/s — tune higher/lower for prop-blur feel
}

// 2) Banner / flag waving — driven on the skinned mesh's root bone.
const BANNER = {
    waveSpeed: 2.2, // main flap frequency
    waveAmplitude: 0.16, // radians, main flap swing
    flutterSpeed: 5.3, // secondary faster flutter frequency
    flutterAmplitude: 0.05, // radians, secondary flutter swing
}

// 3) Decorative "Wind" swirl meshes — slow rotation + gentle float, desynced.
const WIND_OBJECTS = [
    { rotationSpeed: 0.42, floatSpeed: 0.55, floatAmplitude: 0.18, visibleScale: 0.6 },
    { rotationSpeed: 0.61, floatSpeed: 0.38, floatAmplitude: 0.22, visibleScale: 0.6 },
    { rotationSpeed: 0.33, floatSpeed: 0.71, floatAmplitude: 0.14, visibleScale: 0.6 },
]

// 4) Cloud meshes — horizontal drift with seamless wrap-around + gentle bob.
const CLOUD_DRIFT_HALF_RANGE = 45 // world units either side of x = 0 before wrapping
const CLOUD_OBJECTS = [
    { driftSpeed: 1.1, floatSpeed: 0.3, floatAmplitude: 0.6, visibleScale: 1 },
    { driftSpeed: 0.8, floatSpeed: 0.24, floatAmplitude: 0.45, visibleScale: 1 },
    { driftSpeed: 0.95, floatSpeed: 0.34, floatAmplitude: 0.5, visibleScale: 1 },
]

// 5) Airplane idle motion — subtle bob / pitch / roll / vibration so it never sits dead-still.
const IDLE = {
    bobSpeed: 0.9,
    bobAmplitude: 0.06,
    pitchSpeed: 0.6,
    pitchAmplitude: 0.018,
    rollSpeed: 0.5,
    rollAmplitude: 0.022,
    vibrationSpeed: 13,
    vibrationAmplitude: 0.0035,
}

export function Aeroplane(props) {
    const { scene } = useGLTF(CLOUDINARY_URL)
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
    const { nodes, materials } = useGraph(clone)

    /* ---------------- refs used purely for animation ---------------- */

    // Propeller hub group (Object_11 blade + Object_13 wind/motion-line decal).
    const propellerRef = useRef(null)

    // Root bone driving the skinned banner mesh — rotating it makes the whole
    // flag flap since it's the only bone in the chain exposed by gltfjsx.
    const bannerBoneRef = useRef(null)
    const bannerBaseRotation = useRef(new THREE.Euler())

    // Independent floating "wind" swirl decorations (Object_4 / Object_6 / Object_8).
    const windRefs = [useRef(null), useRef(null), useRef(null)]
    const windBasePos = useRef([])

    // Independent drifting cloud meshes (Object_70 / Object_72 / Object_74).
    const cloudRefs = [useRef(null), useRef(null), useRef(null)]
    const cloudBasePos = useRef([])

    // Wrapper group placed ONLY around the physical airplane parts (fuselage,
    // wings/tail meshes, propeller, wheels, banner) — NOT around the wind/cloud
    // decorations, which must drift independently in world space. This is a
    // single, non-renaming, transform-only wrapper; it does not touch any
    // existing node names or the model's internal hierarchy.
    const airplaneGroupRef = useRef(null)

    /* ---------------- capture initial (bind) transforms once ---------------- */

    useEffect(() => {
        if (bannerBoneRef.current) {
            bannerBaseRotation.current.copy(bannerBoneRef.current.rotation)
        }
        windBasePos.current = windRefs.map((r) => r.current?.position.clone() ?? new THREE.Vector3())
        cloudBasePos.current = cloudRefs.map((r) => r.current?.position.clone() ?? new THREE.Vector3())
    }, [])

    /* ---------------- per-frame animation ---------------- */

    useFrame((state, delta) => {
        const t = state.clock.elapsedTime

        // 1) PROPELLER — continuous, fast, frame-rate independent spin about its
        // own local axis (the group's baked rotation already defines that axis).
        if (propellerRef.current) {
            propellerRef.current.rotation.x += PROPELLER.speed * delta
        }

        // 2) BANNER — gentle continuous wave using layered sine waves so the
        // motion never looks like a single robotic back-and-forth snap.
        if (bannerBoneRef.current) {
            const base = bannerBaseRotation.current
            bannerBoneRef.current.rotation.z =
                base.z + Math.sin(t * BANNER.waveSpeed) * BANNER.waveAmplitude
            bannerBoneRef.current.rotation.x =
                base.x + Math.cos(t * BANNER.flutterSpeed) * BANNER.flutterAmplitude
        }

        // 3) WIND OBJECTS — slow rotation + slight float, each mesh desynced via
        // its own speed/phase so nothing moves in lockstep.
        WIND_OBJECTS.forEach((cfg, i) => {
            const mesh = windRefs[i].current
            const base = windBasePos.current[i]
            if (!mesh || !base) return
            mesh.rotation.y += cfg.rotationSpeed * delta
            mesh.position.y = base.y + Math.sin(t * cfg.floatSpeed + i) * cfg.floatAmplitude
        })

        // 4) CLOUDS — slow horizontal drift that wraps seamlessly, plus subtle
        // vertical float. Each cloud has its own drift/float speed.
        CLOUD_OBJECTS.forEach((cfg, i) => {
            const mesh = cloudRefs[i].current
            const base = cloudBasePos.current[i]
            if (!mesh || !base) return
            const raw = base.x + t * cfg.driftSpeed
            // wrap into [-CLOUD_DRIFT_HALF_RANGE, +CLOUD_DRIFT_HALF_RANGE] for a seamless loop
            mesh.position.x =
                (((raw + CLOUD_DRIFT_HALF_RANGE) % (CLOUD_DRIFT_HALF_RANGE * 2)) + CLOUD_DRIFT_HALF_RANGE * 2) %
                (CLOUD_DRIFT_HALF_RANGE * 2) -
                CLOUD_DRIFT_HALF_RANGE
            mesh.position.y = base.y + Math.sin(t * cfg.floatSpeed + i * 1.7) * cfg.floatAmplitude
        })

        // 5) AIRPLANE IDLE MOTION — gentle bob, tiny pitch/roll, and a barely
        // perceptible vibration so the plane always reads as "alive" in the air.
        if (airplaneGroupRef.current) {
            const g = airplaneGroupRef.current
            const vibration = Math.sin(t * IDLE.vibrationSpeed) * IDLE.vibrationAmplitude
            g.position.y = Math.sin(t * IDLE.bobSpeed) * IDLE.bobAmplitude + vibration
            g.rotation.x = Math.sin(t * IDLE.pitchSpeed) * IDLE.pitchAmplitude
            g.rotation.z = Math.cos(t * IDLE.rollSpeed) * IDLE.rollAmplitude
        }
    })

    return (
        <group {...props} dispose={null} position={[0, 5, 0]}>
            <group rotation={[-Math.PI / 2, Math.PI / 6, 0]} scale={0.7}>
                <group rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                    {/* ---- Airplane body wrapper (idle bob / pitch / roll applied here) ---- */}
                    <group ref={airplaneGroupRef}>
                        {/* Propeller hub */}
                        <group ref={propellerRef} position={[-2.431, -0.007, 0.002]} rotation={[0, 0, 0]}>
                            <mesh geometry={nodes.Object_11.geometry} material={materials.Bits} />
                            <mesh geometry={nodes.Object_13.geometry} material={materials.Wind} />
                        </group>

                        {/* Banner / flag (skinned mesh, driven by its root bone) */}
                        <group position={[1.947, -0.248, -0.058]} rotation={[1.558, -0.031, 0.006]}>
                            <group position={[3.197, 0.079, 0.07]} rotation={[-2.924, -1.547, -2.903]}>
                                <primitive object={nodes.GLTF_created_0_rootJoint} ref={bannerBoneRef} />
                                <skinnedMesh
                                    geometry={nodes.Object_31_1.geometry}
                                    material={materials.Bits}
                                    skeleton={nodes.Object_31_1.skeleton}
                                />
                            </group>
                            <mesh geometry={nodes.Object_33.geometry} material={materials.Bits} />
                        </group>

                        {/* Fuselage / body */}
                        <group rotation={[1.57, 0, 0]}>
                            <group position={[-0.72, -0.003, -0.04]}>
                                <mesh geometry={nodes.Object_38.geometry} material={materials.Bits} />
                                <mesh geometry={nodes.Object_40.geometry} material={materials.Body} />
                                <mesh geometry={nodes.Object_42.geometry} material={materials.Window} />
                                <mesh geometry={nodes.Object_45.geometry} material={materials.Bits} />
                                <mesh geometry={nodes.Object_48.geometry} material={materials.Body} />
                                <mesh geometry={nodes.Object_50.geometry} material={materials.Wind} />
                                <mesh geometry={nodes.Object_53.geometry} material={materials.Body} />
                                <mesh geometry={nodes.Object_55.geometry} material={materials.Wind} />
                            </group>
                        </group>

                        {/* Tail */}
                        <mesh
                            geometry={nodes.Object_58.geometry}
                            material={materials.Body}
                            position={[2.078, 0.532, -0.008]}
                            rotation={[1.57, 0, 0.007]}
                        />

                        {/* Wheels */}
                        <group position={[-0.663, 0.964, -1.853]} rotation={[1.57, 0.013, 0]}>
                            <mesh geometry={nodes.Object_61.geometry} material={materials.Bits} />
                            <mesh geometry={nodes.Object_63.geometry} material={materials.Wind} />
                        </group>
                        <group position={[-0.656, 0.969, 1.836]} rotation={[1.57, 0, 0]}>
                            <mesh geometry={nodes.Object_66.geometry} material={materials.Bits} />
                            <mesh geometry={nodes.Object_68.geometry} material={materials.Wind} />
                        </group>
                    </group>

                    {/* ---- Decorative "wind" swirl props — independent drift, NOT part of the airplane wrapper ---- */}
                    <mesh
                        ref={windRefs[0]}
                        geometry={nodes.Object_4.geometry}
                        material={materials.Wind}
                        position={[-39.945, 0.002, -5.266]}
                        scale={WIND_OBJECTS[0].visibleScale}
                    />
                    <mesh
                        ref={windRefs[1]}
                        geometry={nodes.Object_6.geometry}
                        material={materials.Wind}
                        position={[-39.953, 4.091, 0]}
                        scale={WIND_OBJECTS[1].visibleScale}
                    />
                    <mesh
                        ref={windRefs[2]}
                        geometry={nodes.Object_8.geometry}
                        material={materials.Wind}
                        position={[-39.936, -2.723, 2.357]}
                        scale={WIND_OBJECTS[2].visibleScale}
                    />

                    {/* ---- Cloud props — independent horizontal drift with seamless wrap ---- */}
                    <mesh
                        ref={cloudRefs[0]}
                        geometry={nodes.Object_70.geometry}
                        material={materials.Clouds}
                        position={[-39.874, -2.228, -18.549]}
                        scale={CLOUD_OBJECTS[0].visibleScale}
                    />
                    <mesh
                        ref={cloudRefs[1]}
                        geometry={nodes.Object_72.geometry}
                        material={materials.Clouds}
                        position={[-40.882, 13.846, 18.801]}
                        scale={CLOUD_OBJECTS[1].visibleScale}
                    />
                    <mesh
                        ref={cloudRefs[2]}
                        geometry={nodes.Object_74.geometry}
                        material={materials.Clouds}
                        position={[-39.952, -21.126, -0.644]}
                        scale={CLOUD_OBJECTS[2].visibleScale}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload(CLOUDINARY_URL)